[tool.poetry]
name = "audio-offset-finder-v2"
version = "0.1.0"
description = ""
authors = ["Andrew Chen <hello@andrewtheguy.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
numpy = "^1.26.4"
matplotlib = "^3.9.0"
pyloudnorm = "^0.1.1"
andrew_utils= { git = "https://github.com/andrewtheguy/andrew_utils.git", rev = "80a32ac11fdd0bc8d31b590963e4df0891a5863e" }
setuptools = "^69.5.1"
scikit-learn = "^1.5.0"
soundfile = "^0.12.1"

[tool.poetry.group.test.dependencies]
pytest = "^8.2.1"
flake8 = "^7.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
