[project]
name = "audio-pattern-detector"
version = "0.2.4"
description = ""
authors = [{ name = "Andrew Chen", email = "hello@andrewtheguy.com" }]
requires-python = "~=3.12.0"
readme = "README.md"
dependencies = [
    "numpy>=1.26.4,<2",
    "matplotlib>=3.9.0,<4",
    "pyloudnorm>=0.1.1,<0.2",
    "andrew_utils",
    "setuptools>=69.5.1,<70",
    "scikit-learn>=1.5.0,<2",
    "pydub>=0.25.1,<0.26",
]

[dependency-groups]
dev = [
    "pytest>=8.2.1,<9",
    "flake8>=7.0.0,<8",
    "ruff>=0.14.6",
    "basedpyright>=1.34.0",
]

[tool.uv.sources]
andrew_utils = { git = "https://github.com/andrewtheguy/andrew_utils.git", rev = "80a32ac11fdd0bc8d31b590963e4df0891a5863e" }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
